In [1]:
import pandas as pd  
data=pd.read_csv(r'C:\Users\zbook\Documents\AI Project\processes2.csv')
data

,Unnamed: 0,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,seats,max_power (in bph),Mileage Unit,Mileage,Engine (CC)
0,0,Maruti,2014,450000,145500,Diesel,Individual,Manual,First Owner,5,74.00,kmpl,23.40,1248
1,2,Hyundai,2010,225000,127000,Diesel,Individual,Manual,First Owner,5,90.00,kmpl,23.00,1396
2,4,Hyundai,2017,440000,45000,Petrol,Individual,Manual,First Owner,5,81.86,kmpl,20.14,1197
3,7,Toyota,2011,350000,90000,Diesel,Individual,Manual,First Owner,5,67.10,kmpl,23.59,1364
4,8,Ford,2013,200000,169000,Diesel,Individual,Manual,First Owner,5,68.10,kmpl,20.00,1399
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2090,6245,Maruti,2017,425000,12000,Petrol,Individual,Manual,First Owner,5,67.04,kmpl,23.10,998
2091,6246,Toyota,2014,425000,50000,Diesel,Individual,Manual,First Owner,5,67.06,kmpl,23.59,1364
2092,6249,Maruti,2011,200000,73000,Petrol,Individual,Manual,First Owner,5,46.30,kmpl,19.70,796
2093,6253,Maruti,2017,360000,80000,Petrol,Individual,Manual,First Owner,5,67.04,kmpl,20.51,998
2094,6256,Hyundai,2014,475000,80000,Diesel,Individual,Manual,Second Owner,5,88.73,kmpl,22.54,1396

In [2]:
data.nunique()

Unnamed: 0            2095
name                    10
year                    20
selling_price          308
km_driven              372
fuel                     4
seller_type              3
transmission             2
owner                    5
seats                    4
max_power (in bph)      77
Mileage Unit             2
Mileage                 86
Engine (CC)             27
dtype: int64

In [5]:
data["Engine (CC)"].unique()

array([1248, 1396, 1197, 1364, 1399,  796, 1461, 1199, 1462, 1498,  998,
       1598, 1086, 1582,  999, 1497,  799, 1196,  814, 1527,  909,  624,
       1373, 1339, 1405, 1194, 1586])

In [ ]:
data.isnull().sum()

study_hours_per_week              0
sleep_hours_per_day               0
attendance_percentage             0
assignments_completed             0
final_grade                       0
participation_level_Low           0
participation_level_Medium        0
internet_access_Yes               0
parental_education_High School    0
parental_education_Master's       0
parental_education_PhD            0
extracurricular_Yes               0
part_time_job_Yes                 0
dtype: int64

In [ ]:
x = data.drop('final_grade', axis=1)
y = data['final_grade']

In [ ]:
x.head()

,study_hours_per_week,sleep_hours_per_day,attendance_percentage,assignments_completed,participation_level_Low,participation_level_Medium,internet_access_Yes,parental_education_High School,parental_education_Master's,parental_education_PhD,extracurricular_Yes,part_time_job_Yes
0,346,409,449,2,0,1,1,0,0.0,0,1,0
1,219,487,392,5,0,1,1,0,0.0,0,0,0
2,376,36,241,9,0,1,1,0,0.0,0,1,0
3,465,351,115,2,1,0,1,0,0.0,0,1,0
4,201,115,365,3,0,1,1,1,0.0,0,1,0

In [ ]:
y.head()

0    431
1    216
2    285
3    320
4    133
Name: final_grade, dtype: int64

In [ ]:
data.columns

Index(['study_hours_per_week', 'sleep_hours_per_day', 'attendance_percentage',
       'assignments_completed', 'final_grade', 'participation_level_Low',
       'participation_level_Medium', 'internet_access_Yes',
       'parental_education_High School', 'parental_education_Master's',
       'parental_education_PhD', 'extracurricular_Yes', 'part_time_job_Yes'],
      dtype='str')

In [ ]:
from sklearn.preprocessing import LabelEncoder
encoders = {}

def encodeCols(cols):
    for i in cols:
        value = pd.DataFrame({i:data[i].unique()})
        LE = LabelEncoder()
        LE.fit(value)
        data[i] = LE.transform(data[i])
        encoders[i] = LE

columns = ['study_hours_per_week', 'sleep_hours_per_day', 'attendance_percentage',
       'assignments_completed', 'final_grade', 'participation_level_Low',
       'participation_level_Medium', 'internet_access_Yes',
       'parental_education_High School',
       'parental_education_PhD', 'extracurricular_Yes', 'part_time_job_Yes']
encodeCols(columns)

c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\zbook\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\preprocessing\_label.py:103: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
data['attendance_percentage'] = data['attendance_percentage'].fillna(data['attendance_percentage'].mean())

In [ ]:
import joblib
# Save encoders
joblib.dump(encoders, "encoders.pkl")

['encoders.pkl']

In [ ]:
output_path = r'C:\Users\zbook\Documents\AI Project\cleaned_data.csv'

try:
	data.to_csv(output_path, index=False)
except PermissionError:
	output_path = r'C:\Users\zbook\Documents\AI Project\cleaned_data_export.csv'
	data.to_csv(output_path, index=False)
	print(f'Original file was locked. Saved data to {output_path} instead.')

In [ ]:
data.to_csv('cleaned_data.csv', index=False, header=True)